version: "3.7"
services:
    logstash:
        build: ./logstash
        restart: always
        ports:
            - "5044:5044"
        depends_on: 
            - elastic
        networks:
            - elk
    elastic:
        image: elasticsearch:6.8.11
        restart: always
        ports:
            - "9100:9100"
            - "9200:9200"
            - "9300:9300"
        networks:
            - elk
        shm_size: "2GB"
                
    kibana:
        image: kibana:6.8.11
        restart: always
        volumes:
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - "5601:5601"
        depends_on: 
            - elastic
        networks:
            - elk
networks:
    elk:
        driver: bridge
